[package]
name = "tools"
description = "A collection of tools to support the creation of the powerd6 system."
version = "0.1.0"

[workspace]
members = ["fs", "module"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
fs = { path = "./fs" }
module = { path = "./module" }
pretty_assertions = "1.3.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
testdir = "0.7.3"
thiserror = "1.0"
url = { version = "2.3.1", features = ["serde"] }

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
fs = { workspace = true }
module = { workspace = true }
serde_json = { workspace = true }
