[package]
name = "tools"
description = "A collection of tools to support the creation of the powerd6 system."
version = "0.1.0"

[dependencies]

[workspace]
members = [
    "module",
]

[workspace.package]
edition = "2021"