[package]
name = "tools"
description = "A collection of tools to support the creation of the powerd6 system."
version = "0.1.0"

[workspace]
members = ["fs", "module"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
jsonschema = { version = "0.17.0", features = ["draft202012"] }
serde = "1.0.163"
serde_json = "1.0.96"
testdir = "0.7.3"
url = { version = "2.3.1", features =["serde"] }
