[package]
name = "module"
description = "An oxidized representation of the powerd6 modules and their components."
version = "0.1.0"
edition.workspace = true

[dependencies]
fs = { workspace = true }
jsonschema = { workspace = true, features = ["draft202012"] }
serde_json = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
