[package]
name = "module"
description = "An oxidized representation of the powerd6 modules and their components."
version = "0.1.0"
edition.workspace = true

[dependencies]
jsonschema = { workspace = true, features = ["draft202012"] }