name: Validate PR
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: powerd6/.github/.github/workflows/rust-ci.yml@main
    secrets: inherit